### ISSUE TITLE
False positive for conditional protection

### ISSUE THREAD

**Issue by gaborcsardi** [kalibera/rchk#15]
E.g. this code 
```c
#include <R.h>
#include <Rinternals.h>

SEXP foobar(SEXP arg) {
  SEXP xx;
  int carg = INTEGER(arg)[0];

  if (carg > 100 || carg < 0) {
    xx = PROTECT(allocVector(INTSXP, 100));
  }

  if (carg > 100 || carg < 0) {
    UNPROTECT(1);
  }

  return R_NilValue;
}
```

generates

```
Function foobar
  [PB] has negative depth /mnt/works/dummy/src/test.c:14
  [UP] attempt to unprotect more items (1) than protected (0), results will be incomplete /mnt/works/dummy/src/test.c:14
  [PB] has possible protection stack imbalance /mnt/works/dummy/src/test.c:17
Analyzed 1 functions, traversed 27 states.
```

I can easily ignore these false positives, but they also show up in the CRAN checks and CRAN keep telling me to "fix" them.

It would be great to have a way to deal with false positives in general, actually.

**Comment by gaborcsardi** [comment]
Seems like this is a good workaround:

```c

#include <R.h>
#include <Rinternals.h>

SEXP foobar(SEXP arg) {
  SEXP xx;
  int carg = INTEGER(arg)[0];
  int px = 0;

  if (carg > 100 || carg < 0) {
    xx = PROTECT(allocVector(INTSXP, 100));
    px ++;
  }

  UNPROTECT(px);

  return R_NilValue;
}
```

**Comment by kalibera** [comment]
Yes, the tool supports a counter for the number of protected items (`px` in this case). It also models state of some guard variables along branches, but not integer intervals, so that's why it does not remember that the protection depth was different for `carg > 100 || carg < 0`. Conditional protection based on intervals is rare, supporting it would probably not be worth the checking time and the extra programming effort.

**Comment by gaborcsardi** [comment]
I don't actually want integer intervals, just needed a difficult enough condition for an example. I have various conditions, which rchk has basically no chance supporting. Anyway, the counter seems to be good.
