### ISSUE TITLE
Local results from run with singularity differ from CRAN results

### ISSUE THREAD

**Issue by krlmlr** [kalibera/rchk#24]
for the duckdb package.

How can I replicate what CRAN is seeing?

Would it be useful to emit more diagnostic information (LLVM version, ...) for the CRAN runs and perhaps also for local runs?

CC @hannesmuehleisen.

## Locally:

```
$ singularity run kalibera-rchk-master-def.simg duckdb
...

Library name (usually package name): duckdb
Initialization function: R_init_duckdb
Functions: 12
Checked call to R_registerRoutines: 1

Function DataFrameScanFunction::dataframe_scan_bind(duckdb::ClientContext&, std::__1::vector<duckdb::Value, std::__1::allocator<duckdb::Value> >&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, duckdb::Value, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, duckdb::Value> > >&, std::__1::vector<duckdb::LogicalType, std::__1::allocator<duckdb::LogicalType> >&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&)
  [UP] ignoring variable df as it has address taken, results will be incomplete 
Analyzed 24673 functions, traversed 226939 states.
```

## On CRAN

```
Package duckdb version 0.2.1-2
Package built using 79279/R 4.1.0; x86_64-pc-linux-gnu; 2020-09-30 14:05:37 UTC; unix   
Checked with rchk version 36c7ad2294619ba0a81109c9acb675eea2c96e6d
More information at https://github.com/kalibera/cran-checks/blob/master/rchk/PROTECT.md

Function duckdb_execute_R
  [UP] unprotected variable <unnamed var:   %2 = alloca %struct.SEXPREC*, align 8> while calling allocating function std::__1::unique_ptr<duckdb::QueryResult, std::__1::default_delete<duckdb::QueryResult> >::~unique_ptr() duckdb/src/duckdbr.cpp:611
```

**Comment by kalibera** [comment]
I only have time now for a quick response. I get the warning you see on CRAN also in my local run using the latest rchk, but I did not have time to try with singularity, maybe it has an older version, I am going to update that soon also with the documentation for installation on recent systems. My key advice is try to find the problem by looking at your code, not trying to debug/reproduce rchk runs, that can be really complicated particularly with C++, and you would not learn much by that; if you are sure the code is correct then assume it is a false alarm. The error message is saying that a destructor may be run at the end of the function and destroy the (unprotected) return value of the function. So check which destructors are run there and whether you are sure they are not allocating (or whether there would be a trivial change, not complicating the code, which would make such destructors run sooner).

**Comment by kalibera** [comment]
I've updated the singularity image to use latest rchk and to print some version information at the end. Also I've created a variant to use Ubuntu 20.04, but it is not available yet at Singularity Hub, because Singularity Hub does not support debootstrap with Ubuntu 20.04 support. When I built this newer image locally, it reported the issue with `unprotected variable`. The 18.04 image (built by Singularity Hub) did not. I don't know why the difference (the LLVM version is different, compiler, runtime library, all of that could in principle be the cause), maybe the LLVM version, but it is probably not important. If after checking manually you conclude the code is correct, assume it is and rchk report is a false alarm. I've updated the scripts running the CRAN checks to also report LLVM version.
