### ISSUE TITLE
Can we let rchk know that a function preserves its argument?

### ISSUE THREAD

**Issue by lionel-** [kalibera/rchk#29]
The rlang C library implements an alternative to `R_PreserveObject()`: https://github.com/r-lib/rlang/blob/64c02187/src/rlang/obj.c#L11.

Background: `r_preserve()` stores its argument in a hash table that is protected by the namespace of the embedding package. This makes it easier to detect what package is responsible for a memory leak (e.g. using https://github.com/r-lib/memtools) because leaked nodes are dominated by their package namespace. This is also convenient during development with devtools where namespaces are unloaded and reloaded multiple times in a given session because GC of the namespace automatically frees all preserved objects.

Unfortunately it seems that rchk can't figure out that the argument of `r_preserve()` becomes protected. Could we add some sort of marker or attribute to preserving functions to let rchk know about the semantics of that function? Possibly related to #28.

**Comment by kalibera** [comment]
Rchk by design (intentionally) does not support custom protecting functions. If R packages start using their custom protecting functions, they would become harder to read and debug for others not familiar with that custom API. Which may be end users, developers of other packages, or developers of R. So while technically it would be easy to hard-code a name of another function which will be assumed to work like `R_PreserveObject`, or make it somehow configurable to allow any functions doing this, I don't think this is a good idea. If programs want to preserve an object, they should call `R_PreserveObject` directly - and if they wanted to in addition do some book-keeping, they should call another function in addition to doing the book-keeping. 

In principle, the protecting functions in R can be extended in R if such a need arises, and then supported in rchk, but this particular use case does not seem worth supporting to me, because unloading of namespaces in R is unreliable and doesn't really work (and I don't think it could realistically be fixed to reliably work when packages can load arbitrary external libraries), and because it seems to me that such book-keeping should be something in addition to the (standard) R API for protection.

Note that rchk looks at the code after macro expansion, so one might use macros to change "names" of protecting functions, etc. I don't think this is a good idea for the reasons I described, but, that would work with the tool.

So, to clarify, the pattern in #28 is supported when _local_ in a function (and if that didn't work in some case locally, please report, I would try to fix). But it was never meant to work for detecting/allowing custom protecting functions.

**Comment by lionel-** [comment]
> If R packages start using their custom protecting functions, they would become harder to read and debug for others not familiar with that custom API.

To be honest I feel like this argument is a bit unfair. First of all, as you've noted, nothing prevents a wrapper API from renaming R's preserve function. Second, C++ APIs can't be style-linted by rchk so that would only apply to C APIs. By nature the protection semantics of a C API are much easier to understand than C++ ones with much less effort. So not only is it impossible for rchk to enforce the names of protecting functions, there is also no real payoff.

There are good reasons for implementing custom protection functions. I recall a thread where Luke and yourself have recommended implementing custom protection using a doubly-linked list in C++ APIs.


> this particular use case does not seem worth supporting to me, because unloading of namespaces in R is unreliable and doesn't really work

That's true. However I only mentioned this as a happy property that falls off the design of `r_preserve()`. The crucial point is that when preserved objects are dominated by a package namespace it is much easier to find the source of a leak. If you find a big array preserved in R's precious list, you know it's from an object preserved with `R_PreserveObject()` and that's it. With `r_preserve()`, each package has its own precious list which helps narrow down the source of a leak. I think this is a case where using custom protection is a net gain for everyone.

**Comment by kalibera** [comment]
> > If R packages start using their custom protecting functions, they would become harder to read and debug for others not familiar with that custom API.
> 
> To be honest I feel like this argument is a bit unfair. First of all, as you've noted, nothing prevents a wrapper API from renaming R's preserve function.

Nothing prevents a macro wrapper technically, but I still think it is bad practice to wrap these R API calls.`rchk` is not a style-linting tool. It is a bug finding tool, but some of its design and implementation intentionally doesn't allow/support wrapping some APIs, such as protection functions, because I am convinced those are bad practice.

I don't see a contradiction here. If `rchk` were a style-linting tool trying to prevent wrapping, it should be going much further, but it isn't such a tool.

> Second, C++ APIs can't be style-linted by rchk so that would only apply to C APIs. 

There is no difference in how `rchk` treats C and C++ code. It works on the LLVM IR level.

> By nature the protection semantics of a C API are much easier to understand than C++ ones with much less effort. So not only is it impossible for rchk to enforce the names of protecting functions, there is also no real payoff.

> There are good reasons for implementing custom protection functions. I recall a thread where Luke and yourself have recommended implementing custom protection using a doubly-linked list in C++ APIs.

I am not sure about which thread you refer to, but I think  there is a difference between indirectly protecting some objects within a function by adding them to a local list, and providing custom protection functions. The former can be sometimes useful for performance reasons and is used for such in base R, it can be used also in packages. That way of protection is supported in `rchk`.

**Comment by lionel-** [comment]
> Nothing prevents a macro wrapper technically

Unfortunately, I'm finding that issues of double evaluation are a big hindrance to macro-wrapping, except in simple cases. The goal of wrappers API is to improve readability and reduce the chance of mistakes. Using macros often goes counter that.


> some of its design and implementation intentionally doesn't allow/support wrapping some APIs, such as protection functions, because I am convinced those are bad practice.

I respect that you don't like wrapper APIs. However the most popular package on CRAN, Rcpp, is such a wrapper API. I really wish you would let users be the judge of what's good practice or not for their packages. Since rchk is now run as part of CRAN checks, it is now in a gatekeeping position.


> There is no difference in how rchk treats C and C++ code. It works on the LLVM IR level.

Sure. But the way C++ structures computations makes C++ wrapper APIs compatible with rchk by default. Objects are protected on construction and then methods see these objects as non-local data, which rchk correctly interprets as protected. C APIs don't have that luxury.

**Comment by lionel-** [comment]
I'm now double preserving in both the R precious list and the package precious list to work around this limitation. This way we still get namespace-domination of leaks when snapshotting the namespace registry as GC root. Unfortunately double-preserving slows down every GC so I'm still looking for better options, any idea is welcome.

**Comment by kalibera** [comment]
I would say that such checks should not be run in production code/production runs and package code should only use the R protection API, no wrappers, not even macro wrappers. So, if you want to do this completely outside base R, I would say find a way to do a custom build of the packages in which some part of the protection API is replaced by your implementations, e.g. the precious list (either using macros, or dynamic linker tricks, linker options, code rewriting, anything). You would not have a problem with rchk nor with performance overhead of increased tracing time due to double protection. You would not cause pollution of package code just for specific diagnostic purposes.

If you have some very strong examples of leaks involving the precious list, to the point you believe such functionality should be in base R, please let us know (definitely including Luke). In that case we could consider adding some enhanced precious list implementation built e.g. with the strict barrier checking or otherwise optionally. So again packages would still use the R protection API without wrappers, but with a special build of R for the checks.

I think if you wanted to properly detect memory leaks due to objects reachable only from the precious list, you would have to add conservative C stack scanning, anyway. For that you would need a customized build of R. The precious list itself then could e.g. use weak references or something like that. My guess is that we would not want to add conservative stack scanning even optionally to the base R build, certainly not just for detecting memory leaks, so if you wanted to go this far, probably it is natural to simply maintain a patch for R to build a testing R version for these things.

**Comment by lionel-** [comment]
> I would say find a way to do a custom build of the packages in which some part of the protection API is replaced by your implementation

Good idea thanks. I'll switch on package-preservation from the on load hook depending on whether an envvar is set. If not set, only the base precious list will be used.
